#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
out_dir="${1:-$repo_root/reports/java-calibration}"
iterations="${ITERATIONS:-50000}"
anchor_soql_ms="${ANCHOR_SOQL_MS:-35}"
base_ms="${BASE_MS:-500}"
max_weight_ms="${MAX_WEIGHT_MS:-200}"

mkdir -p "$out_dir/build"

javac -d "$out_dir/build" "$repo_root/tools/java-calibration/src/CpuModelBench.java"
java -cp "$out_dir/build" CpuModelBench "$iterations" > "$out_dir/benchmark.csv"

read_ns() {
  local op="$1"
  awk -F, -v key="$op" 'NR > 1 && $1 == key { print $2; exit }' "$out_dir/benchmark.csv"
}

baseline_ns="$(read_ns baseline)"
soql_ns="$(read_ns soql)"
dml_ns="$(read_ns dml)"
json_ns="$(read_ns json)"
clone_ns="$(read_ns clone)"

if [[ -z "$baseline_ns" || -z "$soql_ns" || -z "$dml_ns" || -z "$json_ns" || -z "$clone_ns" ]]; then
  echo "failed: benchmark.csv is missing required operation rows" >&2
  exit 1
fi

adjusted_ns() {
  local raw="$1"
  awk -v raw="$raw" -v base="$baseline_ns" 'BEGIN { v = raw - base; if (v < 1) v = 1; printf "%.0f", v }'
}

adj_soql="$(adjusted_ns "$soql_ns")"
adj_dml="$(adjusted_ns "$dml_ns")"
adj_json="$(adjusted_ns "$json_ns")"
adj_clone="$(adjusted_ns "$clone_ns")"

scaled_ms() {
  local adjusted="$1"
  awk -v adjusted="$adjusted" -v anchor="$anchor_soql_ms" -v ref="$adj_soql" -v cap="$max_weight_ms" 'BEGIN {
    if (ref <= 0) ref = 1;
    v = (adjusted / ref) * anchor;
    if (v < 1) v = 1;
    if (v > cap) v = cap;
    printf "%.0f", v;
  }'
}

soql_ms="$anchor_soql_ms"
dml_ms="$(scaled_ms "$adj_dml")"
json_ms="$(scaled_ms "$adj_json")"
clone_ms="$(scaled_ms "$adj_clone")"

cat > "$out_dir/cpu_model.toml" <<MODEL
[cpu.model]
base_ms = $base_ms
soql_ms = $soql_ms
dml_ms = $dml_ms
json_ms = $json_ms
clone_ms = $clone_ms
MODEL

cat > "$out_dir/README.txt" <<INFO
Generated by tools/java-calibration/run.sh

Inputs:
- iterations=$iterations
- anchor_soql_ms=$anchor_soql_ms
- base_ms=$base_ms
- max_weight_ms=$max_weight_ms

Outputs:
- benchmark.csv
- cpu_model.toml

How to apply:
1) merge cpu_model.toml into your apexgov.toml
2) run: apexgov check <path> --config apexgov.toml
INFO

echo "wrote: $out_dir/benchmark.csv"
echo "wrote: $out_dir/cpu_model.toml"
cat "$out_dir/cpu_model.toml"
